### PR TITLE
Updated phpmyadmin instructions

### PR DESCRIPTION
**Pull request by MikeMcChillin**
DDEV changed the way it uses phpmyadmin so i updated the steps in the readme.

### CODE REVIEW

**Comment by chrismlusk** [comment]
This assumes phpMyAdmin is the default way to manage databases — which, hey, it's free and (I assume?) familiar to web devs. Not a big deal.

Obviously people comfortable with DDEV and the other options know they can keep using whatever they prefer. But, for the purpose of this README helping any new developer get going, I wonder if we stick to the import command DDEV provides and link to the docs so devs can see the options and choose whatever works for them.

> (Optional) If importing an existing project, run `ddev import-db --file=dumpfile.sql.gz`. If you'd like to use a database GUI, see the [DDEV docs](https://ddev.readthedocs.io/en/latest/users/usage/database-management/#database-guis) for available commands.

**Comment by MikeMcChillin** [comment]
I'm cool with your suggestion but also curious what most ppl in the studio are using - I'm 100% phpmyadmin.

**Comment by chrismlusk** [comment]
I pay for TablePlus because I'm a fancy boy. Previously was using Sequel Pro / Sequel Ace for the longest time though.

**Comment by itsmattsoria** [comment]
Jumping into convo here: I personally use TablePlus as well, and I believe @abigailjxn uses Querious? Seems like a mixed bag, so I'm down with pointing to the docs too

**Comment by abigailjxn** [comment]
Yeah, I use Querious, so also down for the docs.

**Pull request merged**
