### PR TITLE
Feature/app directory

### LINKED ISSUE #51: Move Craft into `app` directory
But let's wait on #39 to be pushed through first.

### PR DESCRIPTION
**Pull request by brianjhanson**
Description:
Updates the directory structure to put all the files you need to run the app within an `app` directory. 

We can take or leave commit 280e4fd. With it, you can still run `composer install` in the project root but you have to update module paths accordingly. Without it, module paths stay the same but you have to run `composer install -d app` from the root or cd into `app` before running `composer install`. Mostly  ¯\\_(ツ)_/¯ for me.  I slightly favor having composer stuff out of the `app` directory, but if someone has a strong feeling we can revert that commit.

Closes #51

### CODE REVIEW

**Comment by chrismlusk** [comment]
+1 for `composer.json` in root, because it's super annoying to `cd` back and forth.

**Comment by brianjhanson** [comment]
Unfortunately after testing it a bit more Craft assumes `composer.json` is going to be in the same directory as Craft in more situations than I thought. We could probably work around it, but I'd rather do that down the line.

If you want to avoid `cd`-ing all over, you can use the `-d` argument to specify the composer directory from the project root.

```
composer install -d app
composer update -d app
```

**Comment by brianjhanson** [comment]
Closing this for now because it breaks the `create-project` command. Pretty sure this is because the `composer.json` doesn't appear in the root, which means when you point composer at it as a `repository` it doesn't think it's a package.

So I'm thinking we'll need to find a way to put the `composer.json` file back into the root, but I'll need to mess with it more to figure out how to make that work

**Comment by brianjhanson** [comment]
Just thinking out loud, but [repository templates](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) could be a better solution than our `composer create-project` one anyways

**Comment by michaelramuta** [comment]
Woah that seems really useful

**Pull request closed without merging**
